#!/usr/bin/env python

import sys, os
from notehandler import Main

if __name__ == "__main__":
    if sys.argv[1] in ['-h', '--help', 'help']:
        print("""
        note <category> <tablename> <arguments>

        Writing a note:
            -n / --new / new <your note>

            Example:
                This is my note being stored in the table 'random' in the 'mynotes' category.
                note mynotes random -n 


        Searching in notes:
            -s / --search / search <optional search string>

            If no optional string is provided, all notes in the table will be returned.
            If search string is given, it will return all elements containing the search string. This is case sensitive.

            Example:
                Returning entire table called python in the projects category:
                    note projects python -s

                Searching for note containing string "foo":
                    note projects mynotes -s foo

        Deleting a note:
            -d / --delete / delete <noteID>

            This function will delete the note(s) with provided Id's.
            To delete multiple notes, the ID's should be separated by spaces.
            ID of notes can be found as the lefternmost value while searching the notes.

            Example:
                Deleting note from mynotes with ID 5 from school category:
                    note school mynotes -d 5

                Deleting notes with ID 3, 10, 15 from mynotes in ideas category:
                    note ideas mynotes -d 3 10 15

        Updating a note:
            -u / --update / update <noteID> <new content>

            This function will only update the content of the note for a given noteID. Timestamp will not be updated.

            Example:
                Updating note in random table in mynotes category with ID 1:
                    note mynotes random -u 1 This is my new note.

        Creating a new table for given category:
            <tablename> -c / --create / create

            This function will create a new SQL table in the school schema for the given subject.

            Example:
                Creating the table school.mathematics:
                    note school mathematics -c

        List tables:
            tables / table / .table / .tables

                Lists all tables in the database.

                Example:
                    note tables
        """)
        sys.exit()
    Main(sys.argv[0:])
